spring:
  application:
    name: kafka-upload-service

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging configuration
logging:
  level:
    com.example.kafkaUpload: INFO
    io.temporal: WARN
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.apache.kafka.clients.admin.AdminClient: ERROR
    org.apache.kafka.clients.NetworkClient: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Kafka configuration
kafka:
  bootstrap-servers: localhost:9092
  topic:
    file-processing: file-processing-requests
    processing-results: processing-results
  consumer:
    group-id: file-processors
    auto-offset-reset: earliest
    enable-auto-commit: false
    max-poll-records: 10

# File processing configuration
file-processing:
  test-data-directory: ./test-data
  thumbnails-directory: ./thumbnails
  virus-scan:
    simulation:
      enabled: true
      failure-rate: 0.1  # 10% failure rate
      processing-time-ms: 500  # Average processing time
  thumbnail:
    simulation:
      enabled: true
      failure-rate: 0.05  # 5% failure rate
      processing-time-ms: 300  # Average processing time
    max-width: 200
    max-height: 200
    format: jpg